"""empty message

Revision ID: d5a10bc5289c
Revises: 7007b32cf623
Create Date: 2023-07-07 18:18:57.220318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a10bc5289c'
down_revision = '7007b32cf623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('project_assistant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['assistant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_assistant_id_fkey', 'virtualassistant', ['assistant_id'], ['id'])

    # ### end Alembic commands ###
