"""empty message

Revision ID: e538fa63504b
Revises: da8926073bf3
Create Date: 2023-07-07 20:00:59.770283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e538fa63504b'
down_revision = 'da8926073bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtualassistant')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_rate', sa.Numeric(precision=4, scale=2), nullable=True))
        batch_op.add_column(sa.Column('weekly_availability', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weekly_availability')
        batch_op.drop_column('hourly_rate')

    op.create_table('virtualassistant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hourly_rate', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('weekly_availability', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='virtualassistant_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='virtualassistant_pkey')
    )
    # ### end Alembic commands ###
